import { parseSupplierCSV } from '../lib/supplierData';

const excelData = `Id,CreatedAt,Title,PriceAmount,PriceCurrency,AuthorId,State,ImageCount,CurrentStockQuantity,PublicData,PrivateData,Metadata
68c38751-a904-46ed-80c6-689154ffb8bd,2025-09-12T02:37:05Z,Prototal Denmark – Industrial 3D Printing Service,,,689e48bb-b5fd-47a3-a809-a12d33e388cb,published,1,,"{""TechnologyID"":[""fdm"",""material-jetting"",""mjf"",""sla"",""sls"",""dmls""],""affiliatelinkid"":""https://prototal.dk"",""categoryLevel1"":""europe"",""listingType"":""free-listing"",""location"":{""address"":""Kuldyssen 6 B, 2630 Taastrup, Denmark"",""building"":"" ""},""thermoplasticid"":[""polypropylene-mjf"",""photopolymer-rigid"",""petg"",""pc-or-pc-abs"",""pc"",""pa11-sls"",""pa-12-carbon-filled"",""nylon-pa-12"",""nylon-12-mineral-filled-hst"",""nylon-12-glass-bead-filled-gf"",""nylon-12-flame-retardant-fr"",""nylon-12-aluminum-filled-af"",""nylon-12"",""abs-m30i"",""formlabs-clear-resin"",""abs-like-black"",""abs-white"",""duraform-pa-nylon-12"",""hips"",""carbonfiberreinforcedfilaments""],""transactionProcessAlias"":""default-inquiry/release-1"",""unitType"":""inquiry""}",,
68c2ee83-59cf-4522-9ef0-0e8cb183745d,2025-09-11T15:45:07Z,PrintAWorld – SLA & Metal 3D Printing Services,,,689e48bb-b5fd-47a3-a809-a12d33e388cb,published,1,,"{""TechnologyID"":[""sla"",""slm""],""affiliatelinkid"":""https://prtwd.com/"",""cardStyle"":""white"",""categoryLevel1"":""northamerica"",""listingType"":""free-listing"",""location"":{""address"":""74-12 88th St, Flushing, NY 11385, USA"",""building"":""""},""metalid"":[""stainless-steel-316l""],""photopolymerid"":[""somos-waterclear-ultra-10122"",""formlabs-tough-resin-2000"",""formlabs-standard-resin"",""formlabs-high-temp-resin""],""thermoplasticid"":[""nylon-pa-12"",""abs-m30-stratasys""],""transactionProcessAlias"":""default-inquiry/release-1"",""unitType"":""inquiry""}",,
68c2eb2e-1d84-49c9-b575-7ebc4eb7a163,2025-09-11T15:30:54Z,GoEngineer – Industrial 3D Printing & Additive Manufacturing,,,689e48bb-b5fd-47a3-a809-a12d33e388cb,published,1,,"{""TechnologyID"":[""fdm"",""material-jetting"",""sla"",""dlp"",""saf""],""affiliatelinkid"":""https://www.goengineer.com/"",""cardStyle"":""white"",""categoryLevel1"":""northamerica"",""listingType"":""free-listing"",""location"":{""address"":""739 East Fort Union Blvd, Midvale, UT 84047, USA"",""building"":""""},""thermoplasticid"":[""pei-ultem-1010-stratasys"",""pa-12-carbon-filled"",""petg"",""pei-ultem-9085-stratasys"",""pc-or-pc-abs"",""pc"",""pa-12"",""nylon-pa-12"",""nylon-12"",""abs-m30-stratasys"",""standardpla"",""carbonfiberreinforcedfilaments""],""transactionProcessAlias"":""default-inquiry/release-1"",""unitType"":""inquiry""}",,
68c2e348-4af9-46f7-bbc2-fd37c788160b,2025-09-11T14:57:12Z,3D Print Danmark – Custom 3D Printing & Rapid Prototyping,,,689e48bb-b5fd-47a3-a809-a12d33e388cb,published,1,,"{""affiliatelinkid"":""https://3dprintdanmark.dk/"",""cardStyle"":""white"",""categoryLevel1"":""europe"",""listingType"":""free-listing"",""location"":{""address"":""H. C. Ørsteds Vej 4, 6100 Haderslev, Denmark"",""building"":""""},""thermoplasticid"":[""tpu-70-a-white"",""pp-natural"",""polypropylene-mjf"",""petg"",""abs-like-black"",""abs-m30-stratasys"",""carbonfiberreinforcedfilaments"",""nylon-12"",""standardpla""],""transactionProcessAlias"":""default-inquiry/release-1"",""unitType"":""inquiry""}",,
68c2e05c-d458-4cb8-b030-ee6e3c9a1ad9,2025-09-11T14:44:44Z,Delva – Industrial Metal Additive Manufacturing & Co‑Develop,,,689e48bb-b5fd-47a3-a809-a12d33e388cb,published,1,,"{""TechnologyID"":[""dmls""],""affiliatelinkid"":""https://delva.fi/en/"",""cardStyle"":""white"",""categoryLevel1"":""europe"",""listingType"":""free-listing"",""location"":{""address"":""Laajamäentie 2, 13430 Hämeenlinna, Finland"",""building"":""""},""metalid"":[""stainless-steel-316l"",""inconel-718"",""maraging-steel"",""aluminum-aisi10mg"",""steel""],""transactionProcessAlias"":""default-inquiry/release-1"",""unitType"":""inquiry""}",,
68c2de34-ed43-4d6b-b071-0cd14f7a1a23,2025-09-11T14:35:32Z,TEUFEL Prototypen – SLA & SLS Prototyping Service,,,689e48bb-b5fd-47a3-a809-a12d33e388cb,published,1,,"{""TechnologyID"":[""sls"",""sla""],""affiliatelinkid"":""https://www.teufel-prototypen.de/en/"",""cardStyle"":""main-brand"",""categoryLevel1"":""europe"",""listingType"":""free-listing"",""location"":{""address"":""Veilchenweg 1, 89278 Nersingen, Germany"",""building"":"" ""},""thermoplasticid"":[""nylon-pa-12"",""nylon-12-glass-bead-filled-gf"",""nylon-12-flame-retardant-fr"",""nylon-12""],""transactionProcessAlias"":""default-inquiry/release-1"",""unitType"":""inquiry""}",,
68c2dbb7-6a69-412b-9465-e354474c0e01,2025-09-11T14:24:55Z,Direct 3D Printing – Industrial 3D Printing & Manufacturing,,,689e48bb-b5fd-47a3-a809-a12d33e388cb,published,1,,"{""TechnologyID"":[""dmls"",""fdm"",""material-jetting"",""sla"",""sls""],""affiliatelinkid"":""https://www.direct3dprinting.com.au/"",""cardStyle"":""white"",""categoryLevel1"":""asia"",""categoryLevel2"":""southamerica"",""listingType"":""free-listing"",""location"":{""address"":""33 Yazaki Way, Carrum Downs VIC 3201, Australia"",""building"":""""},""transactionProcessAlias"":""default-inquiry/release-1"",""unitType"":""inquiry""}",,
68c2d90e-0aa2-4f5e-93cb-a234d6209e5d,2025-09-11T14:13:34Z,igus – Wear-Resistant 3D Printing Service,,,689e48bb-b5fd-47a3-a809-a12d33e388cb,published,1,,"{""TechnologyID"":[""fdm"",""sls"",""dlp""],""affiliatelinkid"":""https://www.igus.com/"",""cardStyle"":""white"",""categoryLevel1"":""northamerica"",""listingType"":""free-listing"",""location"":{""address"":""257 Ferris Ave, Rumford, RI 02916, USA"",""building"":""""},""transactionProcessAlias"":""default-inquiry/release-1"",""unitType"":""inquiry""}",,
68c2d61e-9321-4503-852c-7024ecc441d6,2025-09-11T14:01:02Z,Ultimate 3D Printing Services – Professional 3D Printing & A,,,689e48bb-b5fd-47a3-a809-a12d33e388cb,published,1,,"{""TechnologyID"":[""material-jetting"",""mjf"",""sla"",""sls"",""fdm"",""dmls"",""dlp""],""affiliatelinkid"":""https://ultimate3dprintingservices.com/"",""cardStyle"":""main-brand"",""categoryLevel1"":""northamerica"",""listingType"":""free-listing"",""location"":{""address"":""1851 Gunn Hwy, Odessa, FL 33556, USA"",""building"":""""},""metalid"":[""steel"",""aluminum-aisi10mg"",""titanium-ti-6al-4v"",""stainless-steel-316l"",""maraging-steel"",""inconel-625""],""photopolymerid"":[""formlabs-durable-resin"",""formlabs-flexible-resin-80a"",""ultem-9085""],""thermoplasticid"":[""tpu-70-a-white"",""tpu-mjf"",""pp-natural"",""polypropylene-mjf"",""photopolymer-rigid"",""petg"",""pei-ultem-9085-stratasys"",""pei-ultem-1010-stratasys"",""pc-or-pc-abs"",""pc"",""pa11-sls"",""pa-af"",""pa-gf"",""pa-12-carbon-filled"",""pa-12"",""nylon-pa-12"",""nylon-12-mineral-filled-hst"",""nylon-12-glass-bead-filled-gf"",""nylon-12-flame-retardant-fr"",""nylon-12-aluminum-filled-af"",""nylon-12"",""absplus-stratasys"",""accura-25"",""standardpla"",""carbonfiberreinforcedfilaments"",""mjf_pa12"",""sls_flexible_tpu"",""saf_pa11_eco"",""ultrasint_tpu01_mjf"",""sls_pa12_pa2200""],""transactionProcessAlias"":""default-inquiry/release-1"",""unitType"":""inquiry""}",,
68c2d13e-9c64-4999-80da-d67358d5d11e,2025-09-11T13:40:14Z,Cosine Additive – Large Scale 3D Printing & AM Systems,,,689e48bb-b5fd-47a3-a809-a12d33e388cb,published,1,,"{""TechnologyID"":[""fdm""],""affiliatelinkid"":""https://www.cosineadditive.com/"",""cardStyle"":""white"",""categoryLevel1"":""northamerica"",""listingType"":""free-listing"",""location"":{""address"":""8181 W Hardy Rd, Houston, TX 77022, USA"",""building"":""""},""photopolymerid"":[""polypropylene-p""],""thermoplasticid"":[""standardpla"",""carbonfiberreinforcedfilaments"",""abs-m30-stratasys"",""polypropylene-mjf"",""petg"",""pp-natural"",""pc""],""transactionProcessAlias"":""default-inquiry/release-1"",""unitType"":""inquiry""}",,`;

export async function convertAndUpdateSuppliers() {
  try {
    // Process the new data
    const newSuppliers = await parseSupplierCSV(excelData);
    
    // Convert back to CSV format for storage
    const csvHeader = 'Id,CreatedAt,Title,PriceAmount,PriceCurrency,AuthorId,State,ImageCount,CurrentStockQuantity,PublicData,PrivateData,Metadata';
    const csvRows = newSuppliers.map(supplier => {
      // This is a simplified conversion - in a real scenario you'd need to reconstruct the full PublicData JSON
      return `${supplier.id},${new Date().toISOString()},${supplier.name},,,,published,1,,"{""location"":{""address"":""${supplier.location || ''}""},""TechnologyID"":[],""thermoplasticid"":[],""metalid"":[],""photopolymerid"":[]}",{},`;
    });
    
    const fullCSV = [csvHeader, ...csvRows].join('\n');
    
    return fullCSV;
  } catch (error) {
    console.error('Error converting Excel data:', error);
    throw error;
  }
}