-- Supplier orphan remediation — generated by scripts/audit-seed-orphans-remediate.mjs
-- Generated: 2026-04-23T13:35:09.511Z
-- Safe: each ADD uses ON CONFLICT DO NOTHING; REMOVEs are explicit DELETE WHERE supplier_id=? AND material_id=?
-- Review before running with `npx supabase db push`.

BEGIN;

-- ==========================================================
-- ADD-TECH: 38 (supplier, technology) pairs to insert
--   Evidence: metadata.TechnologyID or description mentions a tech
--   compatible with an orphaned material the supplier already has.
-- ==========================================================

-- 3DCeram: ADD tech "CNC Milling" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Copper (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('d67422ef-7779-49d0-a9e9-bdecfc0203c1', '1e2b5b59-87fe-4adb-974a-cf24d39de31f')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- 3Diligent: ADD tech "Injection Molding" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Silicone (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('812a97b5-2db5-4b51-88c0-e3f0d8d4ff07', '2872606a-f31f-4ccb-857d-9b42746dccb6')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- Applied Rapid Technologies: ADD tech "FDM" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: PC (Polycarbonate) (material-orphan); PEEK (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('749a5d45-af67-4a6f-b5a9-28289ac932b0', '70bc2a43-b906-45e5-bef2-9b572fed9a2e')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- Articon: ADD tech "FDM" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: PEEK (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('ac62d9e2-9d21-4ce2-8b0a-6d7840950d09', '70bc2a43-b906-45e5-bef2-9b572fed9a2e')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- Articon: ADD tech "Binder Jetting" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Cobalt Chrome (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('ac62d9e2-9d21-4ce2-8b0a-6d7840950d09', 'b6abe667-b884-4117-a168-404ef8563454')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- EXL PROTOTYPES CO LTD: ADD tech "CNC Milling" to cover orphaned materials: ABS (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('d4934d0a-f3c6-4fa1-8f72-79e91ac5cb4a', '1e2b5b59-87fe-4adb-974a-cf24d39de31f')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- Fab.Pub: ADD tech "SLA" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Ceramic (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('01090d08-7ecb-429b-9fa6-c0cd69eb8a83', 'f0f48123-c6ed-48fc-b099-c42b4239e45e')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- Geomiq: ADD tech "Injection Molding" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Silicone (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('d0cea5ca-2586-4ad7-85cb-4effbd02213a', '2872606a-f31f-4ccb-857d-9b42746dccb6')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- Guaranteed: ADD tech "CNC Milling" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Bronze (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('a64b2574-8f01-41db-bd12-c9743d74faa4', '1e2b5b59-87fe-4adb-974a-cf24d39de31f')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- i.materialise – Online 3D Printing Service: ADD tech "CNC Milling" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Brass (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('b06b7492-1c4b-4505-844a-b88ffa5f0390', '1e2b5b59-87fe-4adb-974a-cf24d39de31f')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- i.materialise – Online 3D Printing Service: ADD tech "SLM" to cover orphaned materials: Aluminum AlSi10Mg (material-orphan); Inconel 718 (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('b06b7492-1c4b-4505-844a-b88ffa5f0390', '4445d579-5029-492e-af11-78c3b6491c5a')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- in3Dtec: ADD tech "CNC Milling" to cover orphaned materials: Aluminum 6061 (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('9c02358d-6463-48e0-ad37-2323af2a1a2a', '1e2b5b59-87fe-4adb-974a-cf24d39de31f')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- JawsTec – Online 3D Printing Service: ADD tech "CNC Milling" to cover orphaned materials: Aluminum 6061 (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('6f7165ed-87b0-41ae-9076-216f6b7343b4', '1e2b5b59-87fe-4adb-974a-cf24d39de31f')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- Jiga: ADD tech "CNC Milling" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Bronze (material-orphan); Brass (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('46d35e40-8044-42fb-bd12-6bec39e1e42d', '1e2b5b59-87fe-4adb-974a-cf24d39de31f')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- LaMáquina: ADD tech "SLA" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Ceramic (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('9793df47-6730-4b17-b06d-c053090477c0', 'f0f48123-c6ed-48fc-b099-c42b4239e45e')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- Machinified – Additive Manufacturing & Digital Production Pl: ADD tech "CNC Milling" to cover orphaned materials: Aluminum 6061 (material-orphan); Aluminum 7075 (material-orphan); Brass (material-orphan); Bronze (material-orphan); Copper (material-orphan) (+2 more)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('922e07af-9a20-43c7-a53b-f8287a57d762', '1e2b5b59-87fe-4adb-974a-cf24d39de31f')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- NanoFract UG: ADD tech "SLA" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Ceramic (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('e9e23c3c-eb42-4188-b4b6-cb2ca086b01c', 'f0f48123-c6ed-48fc-b099-c42b4239e45e')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- NanoFract UG: ADD tech "SLM" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Tool Steel (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('e9e23c3c-eb42-4188-b4b6-cb2ca086b01c', '4445d579-5029-492e-af11-78c3b6491c5a')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- NanoFract UG: ADD tech "CNC Milling" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Brass (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('e9e23c3c-eb42-4188-b4b6-cb2ca086b01c', '1e2b5b59-87fe-4adb-974a-cf24d39de31f')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- One Off Robotics: ADD tech "SLA" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Ceramic (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('f6369f78-d0b4-4069-bab3-03a4a78e53b5', 'f0f48123-c6ed-48fc-b099-c42b4239e45e')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- OriginLabs - Penn State: ADD tech "FDM" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: ABS (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('e135f7fc-7354-4a19-bc4b-9ea14ffe0b74', '70bc2a43-b906-45e5-bef2-9b572fed9a2e')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- Ponoko: ADD tech "Sheet Metal" to cover orphaned materials: Brass (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('2b82c31f-a61a-43f7-9067-05925cad6a4b', 'dc7a5410-8be9-4508-9bef-cb462bd195a2')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- Ponoko: ADD tech "Injection Molding" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Silicone (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('2b82c31f-a61a-43f7-9067-05925cad6a4b', '2872606a-f31f-4ccb-857d-9b42746dccb6')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- Print a Thing: ADD tech "CNC Milling" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Bronze (material-orphan); Brass (material-orphan); Copper (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('0fed7ece-831f-4b1c-8335-3f647b1000ab', '1e2b5b59-87fe-4adb-974a-cf24d39de31f')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- PrintAWorld – SLA & Metal 3D Printing Services: ADD tech "FDM" to cover orphaned materials: ABS (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('9f7d8701-6c15-4c60-bad5-e63b78e0801a', '70bc2a43-b906-45e5-bef2-9b572fed9a2e')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- Protolabs – Digital Manufacturing & Rapid Prototyping: ADD tech "CNC Milling" to cover orphaned materials: Brass (material-orphan); Copper (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('d6f0224b-66de-4c1a-85b2-c9643865d053', '1e2b5b59-87fe-4adb-974a-cf24d39de31f')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- Robot faber: ADD tech "SLA" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Ceramic (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('6717df62-91b1-4cc6-a9b4-48cb4b248b21', 'f0f48123-c6ed-48fc-b099-c42b4239e45e')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- Sciaky: ADD tech "SLM" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Inconel 625 (material-orphan); Tungsten (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('7a98b849-46a0-4154-bd95-18a9da40833e', '4445d579-5029-492e-af11-78c3b6491c5a')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- Sciaky: ADD tech "CNC Milling" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Copper (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('7a98b849-46a0-4154-bd95-18a9da40833e', '1e2b5b59-87fe-4adb-974a-cf24d39de31f')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- Sculpteo – On-Demand 3D Printing & Digital Manufacturing: ADD tech "CNC Milling" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Brass (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('36a72efd-3b62-4e6e-b401-3fc878f6f210', '1e2b5b59-87fe-4adb-974a-cf24d39de31f')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- THINK3D: ADD tech "CNC Milling" to cover orphaned materials: ABS (material-orphan); Brass (material-orphan); Cobalt Chrome (material-orphan); Copper (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('177b476c-03f8-4341-bd22-afdbac981bd6', '1e2b5b59-87fe-4adb-974a-cf24d39de31f')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- THINK3D: ADD tech "FDM" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Carbon Fiber (material-orphan); Kevlar (material-orphan); TPU (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('177b476c-03f8-4341-bd22-afdbac981bd6', '70bc2a43-b906-45e5-bef2-9b572fed9a2e')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- Treatstock – On-Demand Manufacturing Platform & Marketplace: ADD tech "FDM" to cover orphaned materials: PETG (material-orphan); Carbon Fiber (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('49af8215-583b-47bf-8a49-a4c21315b4ee', '70bc2a43-b906-45e5-bef2-9b572fed9a2e')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- Treddy: ADD tech "FDM" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Carbon Fiber (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('7d3ebc7f-2804-4bd3-bc63-eb2bb135b7be', '70bc2a43-b906-45e5-bef2-9b572fed9a2e')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- TriMech Advanced Manufacturing Services: ADD tech "Injection Molding" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Silicone (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('e3ecfc87-e34a-427f-ab8c-b53e1e54e9fa', '2872606a-f31f-4ccb-857d-9b42746dccb6')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- WAAM3D: ADD tech "CNC Milling" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Bronze (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('e0e7b6de-40c4-4420-b7bf-d9ec8bd28ee5', '1e2b5b59-87fe-4adb-974a-cf24d39de31f')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- WAAM3D: ADD tech "SLM" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: Tungsten (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('e0e7b6de-40c4-4420-b7bf-d9ec8bd28ee5', '4445d579-5029-492e-af11-78c3b6491c5a')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- Xometry: ADD tech "FDM" (REPRESENTATIVE-FALLBACK: supplier has material but no compatible tech in data) to cover orphaned materials: ASA (material-orphan); Carbon Fiber (material-orphan); PPS (material-orphan); TPU (material-orphan)
INSERT INTO supplier_technologies (supplier_id, technology_id)
VALUES ('2dcd031d-4f68-4e14-8c54-eea2bf134409', '70bc2a43-b906-45e5-bef2-9b572fed9a2e')
ON CONFLICT (supplier_id, technology_id) DO NOTHING;

-- ==========================================================
-- ADD-MATERIAL: 117 (supplier, material) pairs to insert
--   Evidence: supplier's Addidex metadata (metalid / thermoplasticid / photopolymerid)
--   contains a material compatible with an orphaned technology the supplier already has.
--   Fallback rows (marked) use generic bridged materials when no metadata evidence exists.
-- ==========================================================

-- 3D Makers Zone: ADD material "Titanium" (FALLBACK generic) to cover orphaned techs: EBM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('53c84a0a-2d29-4f97-bbdf-9ab4de2b6bfd', '016504b7-b2f7-42be-8558-68c01b1749ab')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- 3D Printing Services: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLS (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('208baa7f-0fca-473e-917a-db478c3a988a', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- 3D Printing Services: ADD material "Titanium" (FALLBACK generic) to cover orphaned techs: Binder Jetting (tech-orphan); SLM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('208baa7f-0fca-473e-917a-db478c3a988a', '016504b7-b2f7-42be-8558-68c01b1749ab')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- 3D Systems: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLS (tech-orphan); MJF (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('06637a03-2f55-467f-b9af-afbe99fbf149', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- 3D Systems: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan); DLP (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('06637a03-2f55-467f-b9af-afbe99fbf149', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- 3DCeram: ADD material "PLA" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: FDM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('d67422ef-7779-49d0-a9e9-bdecfc0203c1', 'ee64ec57-3edb-4ec5-8999-849b8aa91953')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- 3Diligent: ADD material "PLA" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: FDM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('812a97b5-2db5-4b51-88c0-e3f0d8d4ff07', 'ee64ec57-3edb-4ec5-8999-849b8aa91953')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- 3Diligent: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan); DLP (tech-orphan); Material Jetting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('812a97b5-2db5-4b51-88c0-e3f0d8d4ff07', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- 3Diligent: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLS (tech-orphan); MJF (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('812a97b5-2db5-4b51-88c0-e3f0d8d4ff07', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- 3Diligent: ADD material "Titanium" (FALLBACK generic) to cover orphaned techs: SLM (tech-orphan); EBM (tech-orphan); Binder Jetting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('812a97b5-2db5-4b51-88c0-e3f0d8d4ff07', '016504b7-b2f7-42be-8558-68c01b1749ab')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- 3ERP – Rapid Prototyping & Low-Volume Manufacturing Services: ADD material "Titanium Ti6Al4V" to cover orphaned techs: CNC Machining (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('27465667-990b-4bf1-a93b-9b5fd03f9d80', '09b3a5ed-bd9c-4a15-b4f0-1f6a4e730599')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- 3ERP – Rapid Prototyping & Low-Volume Manufacturing Services: ADD material "PEI (Ultem)" to cover orphaned techs: Injection Molding (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('27465667-990b-4bf1-a93b-9b5fd03f9d80', 'e028fb91-cd96-44c5-95f9-89f337b159ab')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Additive Manufacturing, LLC: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLS (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('9b3402f3-feb1-4ce2-b421-053871aaefa5', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Additive Manufacturing, LLC: ADD material "Titanium" (FALLBACK generic) to cover orphaned techs: SLM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('9b3402f3-feb1-4ce2-b421-053871aaefa5', '016504b7-b2f7-42be-8558-68c01b1749ab')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- ADDMAN: ADD material "PP (Polypropylene)" to cover orphaned techs: MJF (tech-orphan); FDM (tech-orphan); SLS (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('174cc44a-7191-46e7-9d60-a130114eaec3', 'f4d96323-3e38-4f64-a6e8-6cc09fa4edd4')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- ADDMAN: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan); DLP (tech-orphan); Material Jetting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('174cc44a-7191-46e7-9d60-a130114eaec3', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- ADDMAN: ADD material "Titanium Ti6Al4V" to cover orphaned techs: CNC Milling (tech-orphan); CNC Turning (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('174cc44a-7191-46e7-9d60-a130114eaec3', '09b3a5ed-bd9c-4a15-b4f0-1f6a4e730599')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- ADDMAN: ADD material "Aluminum AlSi10Mg" to cover orphaned techs: SLM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('174cc44a-7191-46e7-9d60-a130114eaec3', '9b4d1155-a23b-4a88-9ad8-3e38bc83b940')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- American Additive Manufacturing: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('0cbb7d18-1625-410d-9f09-ae3a2fa7a0de', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- American Additive Manufacturing: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: MJF (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('0cbb7d18-1625-410d-9f09-ae3a2fa7a0de', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- American Additive Manufacturing: ADD material "Titanium" (FALLBACK generic) to cover orphaned techs: SLM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('0cbb7d18-1625-410d-9f09-ae3a2fa7a0de', '016504b7-b2f7-42be-8558-68c01b1749ab')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Articon: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: DLP (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('ac62d9e2-9d21-4ce2-8b0a-6d7840950d09', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- BaessTech Engineering: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLS (tech-orphan); MJF (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('cc000001-0006-4000-8000-000000000006', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- BaessTech Engineering: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('cc000001-0006-4000-8000-000000000006', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Direct 3D Printing – Industrial 3D Printing & Manufacturing: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLS (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('f3d14ef9-0d1c-400d-aaf4-5c1630c49fed', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Direct 3D Printing – Industrial 3D Printing & Manufacturing: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan); Material Jetting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('f3d14ef9-0d1c-400d-aaf4-5c1630c49fed', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Direct 3D Printing – Industrial 3D Printing & Manufacturing: ADD material "PA11 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SAF (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('f3d14ef9-0d1c-400d-aaf4-5c1630c49fed', '8ffd5af5-d35b-49fc-921f-809b0f893345')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- EXL PROTOTYPES CO LTD: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan); Material Jetting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('d4934d0a-f3c6-4fa1-8f72-79e91ac5cb4a', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- EXL PROTOTYPES CO LTD: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLS (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('d4934d0a-f3c6-4fa1-8f72-79e91ac5cb4a', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- EXL PROTOTYPES CO LTD: ADD material "Titanium" (FALLBACK generic) to cover orphaned techs: SLM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('d4934d0a-f3c6-4fa1-8f72-79e91ac5cb4a', '016504b7-b2f7-42be-8558-68c01b1749ab')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- FIT Additive Manufacturing Group: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLS (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('0fa22345-ea0b-408d-b953-0ea8564ad96b', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Forecast 3D – Industrial 3D Printing & Digital Manufacturing: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan); Material Jetting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('c1588a55-cd74-463a-a3f2-8e15cae47a90', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Forecast 3D – Industrial 3D Printing & Digital Manufacturing: ADD material "Maraging Steel" to cover orphaned techs: SLM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('c1588a55-cd74-463a-a3f2-8e15cae47a90', 'ee43875d-1941-4910-8461-997ffd070740')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Foremost AddiTech: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('42322d5b-930a-4af5-b84a-c267e48af747', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- FORMES ET VOLUMES: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: Material Jetting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('4cfe6688-a4df-4228-9eb0-5d25747b0a22', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Geomiq: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan); Material Jetting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('d0cea5ca-2586-4ad7-85cb-4effbd02213a', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Geomiq: ADD material "PLA" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: FDM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('d0cea5ca-2586-4ad7-85cb-4effbd02213a', 'ee64ec57-3edb-4ec5-8999-849b8aa91953')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Geomiq: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLS (tech-orphan); MJF (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('d0cea5ca-2586-4ad7-85cb-4effbd02213a', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Geomiq: ADD material "Titanium" (FALLBACK generic) to cover orphaned techs: CNC Machining (tech-orphan); SLM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('d0cea5ca-2586-4ad7-85cb-4effbd02213a', '016504b7-b2f7-42be-8558-68c01b1749ab')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Geomiq: ADD material "Aluminum AlSi10Mg" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: Die Casting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('d0cea5ca-2586-4ad7-85cb-4effbd02213a', '9b4d1155-a23b-4a88-9ad8-3e38bc83b940')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- HabitAdd: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLS (tech-orphan); MJF (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('dea9911e-81e0-4108-90f0-6ab4dfb7b1d9', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- HabitAdd: ADD material "Titanium" (FALLBACK generic) to cover orphaned techs: SLM (tech-orphan); DED (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('dea9911e-81e0-4108-90f0-6ab4dfb7b1d9', '016504b7-b2f7-42be-8558-68c01b1749ab')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- HabitAdd: ADD material "PLA" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: FDM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('dea9911e-81e0-4108-90f0-6ab4dfb7b1d9', 'ee64ec57-3edb-4ec5-8999-849b8aa91953')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- HLH Prototypes: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('57ebb37b-0d2a-4116-9487-6a2295a29909', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- HLH Prototypes: ADD material "Titanium" (FALLBACK generic) to cover orphaned techs: CNC Machining (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('57ebb37b-0d2a-4116-9487-6a2295a29909', '016504b7-b2f7-42be-8558-68c01b1749ab')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- HLH Prototypes: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: Injection Molding (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('57ebb37b-0d2a-4116-9487-6a2295a29909', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- HLH Prototypes: ADD material "Aluminum AlSi10Mg" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: Die Casting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('57ebb37b-0d2a-4116-9487-6a2295a29909', '9b4d1155-a23b-4a88-9ad8-3e38bc83b940')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Holit: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('394a5668-390d-42ce-9814-9c06d4b1951e', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Holit: ADD material "Titanium" (FALLBACK generic) to cover orphaned techs: SLM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('394a5668-390d-42ce-9814-9c06d4b1951e', '016504b7-b2f7-42be-8558-68c01b1749ab')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- i.materialise – Online 3D Printing Service: ADD material "Tough Resin" to cover orphaned techs: SLA (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('b06b7492-1c4b-4505-844a-b88ffa5f0390', 'ff6a5242-a92a-49dc-9049-4b3f7d06368b')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Imaginarium: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan); DLP (tech-orphan); Material Jetting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('e7272ef9-b285-4938-9f10-2555107cb19c', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Imaginarium: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLS (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('e7272ef9-b285-4938-9f10-2555107cb19c', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- JLC3DP – Online 3D Printing Service: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('6929af49-c9ee-4fe6-8045-bd05e137b581', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- JLC3DP – Online 3D Printing Service: ADD material "Aluminum AlSi10Mg" to cover orphaned techs: SLM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('6929af49-c9ee-4fe6-8045-bd05e137b581', '9b4d1155-a23b-4a88-9ad8-3e38bc83b940')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- JLC3DP – Online 3D Printing Service: ADD material "Titanium Ti6Al4V" to cover orphaned techs: Binder Jetting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('6929af49-c9ee-4fe6-8045-bd05e137b581', '09b3a5ed-bd9c-4a15-b4f0-1f6a4e730599')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Machinified – Additive Manufacturing & Digital Production Pl: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan); DLP (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('922e07af-9a20-43c7-a53b-f8287a57d762', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Machinified – Additive Manufacturing & Digital Production Pl: ADD material "TPU" to cover orphaned techs: MJF (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('922e07af-9a20-43c7-a53b-f8287a57d762', '12522e48-ded9-4387-8a0e-1b0f78350098')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Makelab: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('b9b197fb-49e0-459e-bc87-9aef88e53331', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Makelab: ADD material "TPU" to cover orphaned techs: MJF (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('b9b197fb-49e0-459e-bc87-9aef88e53331', '12522e48-ded9-4387-8a0e-1b0f78350098')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Materialise OnSite: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan); Material Jetting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('e6db73d6-ca15-4e2e-983f-a58a17c33870', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Materialise OnSite: ADD material "Titanium" (FALLBACK generic) to cover orphaned techs: SLM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('e6db73d6-ca15-4e2e-983f-a58a17c33870', '016504b7-b2f7-42be-8558-68c01b1749ab')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- NanoFract UG: ADD material "PLA" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: FDM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('e9e23c3c-eb42-4188-b4b6-cb2ca086b01c', 'ee64ec57-3edb-4ec5-8999-849b8aa91953')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Plus Manufact GmbH: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: MJF (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('f115bb46-26d8-4823-8b1e-1f43452e084c', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Ponoko: ADD material "PLA" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: FDM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('2b82c31f-a61a-43f7-9067-05925cad6a4b', 'ee64ec57-3edb-4ec5-8999-849b8aa91953')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- PrintAWorld – SLA & Metal 3D Printing Services: ADD material "Tough Resin" to cover orphaned techs: SLA (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('9f7d8701-6c15-4c60-bad5-e63b78e0801a', 'ff6a5242-a92a-49dc-9049-4b3f7d06368b')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Printerior: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('b1113130-d469-4d2a-8060-cfd21104b71d', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Printerior: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLS (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('b1113130-d469-4d2a-8060-cfd21104b71d', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Prosilas (Prototal Prosilas): ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('b4b30f06-4db1-4b5a-989b-e45c4057c9aa', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Prosilas (Prototal Prosilas): ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: Injection Molding (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('b4b30f06-4db1-4b5a-989b-e45c4057c9aa', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- PROTIQ – Digital Manufacturing Marketplace & 3D Printing Sol: ADD material "PP (Polypropylene)" to cover orphaned techs: SLS (tech-orphan); MJF (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('3630901a-f01d-4578-a719-a63cb5338e4f', 'f4d96323-3e38-4f64-a6e8-6cc09fa4edd4')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Proto3000: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLS (tech-orphan); MJF (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('ae811dfd-af2f-4381-96e5-5025587c978b', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Proto3000: ADD material "Titanium" (FALLBACK generic) to cover orphaned techs: SLM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('ae811dfd-af2f-4381-96e5-5025587c978b', '016504b7-b2f7-42be-8558-68c01b1749ab')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Protolabs – Digital Manufacturing & Rapid Prototyping: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('d6f0224b-66de-4c1a-85b2-c9643865d053', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Protolabs – Digital Manufacturing & Rapid Prototyping: ADD material "PA12 Nylon" to cover orphaned techs: SLS (tech-orphan); FDM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('d6f0224b-66de-4c1a-85b2-c9643865d053', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Prototal Denmark – Industrial 3D Printing Service: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan); Material Jetting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('49af0085-6e50-4f8d-bbeb-9e330c979957', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Prototal Denmark – Industrial 3D Printing Service: ADD material "PP (Polypropylene)" to cover orphaned techs: SAF (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('49af0085-6e50-4f8d-bbeb-9e330c979957', 'f4d96323-3e38-4f64-a6e8-6cc09fa4edd4')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Prototek: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan); DLP (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('817d58f1-da2f-43a9-9887-c04564b1af59', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Quickparts – Rapid Prototyping & Manufacturing Services: ADD material "PC (Polycarbonate)" to cover orphaned techs: Injection Molding (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('49cb1ca6-6451-4459-ade9-c698e9098998', '9d6d5ff3-e04d-46b4-8272-c8bde69605bc')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Quickparts – Rapid Prototyping & Manufacturing Services: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan); DLP (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('49cb1ca6-6451-4459-ade9-c698e9098998', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Quickparts – Rapid Prototyping & Manufacturing Services: ADD material "PA11 Nylon" to cover orphaned techs: SLS (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('49cb1ca6-6451-4459-ade9-c698e9098998', '8ffd5af5-d35b-49fc-921f-809b0f893345')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Quickparts – Rapid Prototyping & Manufacturing Services: ADD material "Aluminum AlSi10Mg" to cover orphaned techs: Die Casting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('49cb1ca6-6451-4459-ade9-c698e9098998', '9b4d1155-a23b-4a88-9ad8-3e38bc83b940')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- RapidDirect: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('c7d7ba5d-ec07-4c8d-8ea5-07e8d512f367', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- RapidDirect: ADD material "PA12 Nylon" to cover orphaned techs: MJF (tech-orphan); SLS (tech-orphan); Injection Molding (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('c7d7ba5d-ec07-4c8d-8ea5-07e8d512f367', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- RapidDirect: ADD material "Aluminum AlSi10Mg" to cover orphaned techs: Die Casting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('c7d7ba5d-ec07-4c8d-8ea5-07e8d512f367', '9b4d1155-a23b-4a88-9ad8-3e38bc83b940')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- RapidMade – 3D Printing & Digital Manufacturing Services: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan); DLP (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('15c09d77-9c34-40e2-a0b4-0795ccc45316', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- RapidMade – 3D Printing & Digital Manufacturing Services: ADD material "Aluminum AlSi10Mg" to cover orphaned techs: SLM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('15c09d77-9c34-40e2-a0b4-0795ccc45316', '9b4d1155-a23b-4a88-9ad8-3e38bc83b940')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Robot faber: ADD material "PLA" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: FDM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('6717df62-91b1-4cc6-a9b4-48cb4b248b21', 'ee64ec57-3edb-4ec5-8999-849b8aa91953')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- RYSE 3D: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: MJF (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('cc000001-0003-4000-8000-000000000003', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Sculpteo – On-Demand 3D Printing & Digital Manufacturing: ADD material "Flexible Resin" to cover orphaned techs: SLA (tech-orphan); DLP (tech-orphan); Material Jetting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('36a72efd-3b62-4e6e-b401-3fc878f6f210', 'a3668078-2dd7-4570-bd9f-9fa2516176f7')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Sculpteo – On-Demand 3D Printing & Digital Manufacturing: ADD material "Aluminum AlSi10Mg" to cover orphaned techs: SLM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('36a72efd-3b62-4e6e-b401-3fc878f6f210', '9b4d1155-a23b-4a88-9ad8-3e38bc83b940')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Sculpteo – On-Demand 3D Printing & Digital Manufacturing: ADD material "Standard Resin" to cover orphaned techs: LCD (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('36a72efd-3b62-4e6e-b401-3fc878f6f210', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- SGD 3D: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('47f54c99-098b-47a7-b9f2-b5189c68808c', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Shapeways: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: MJF (tech-orphan); SLS (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('103247e7-ac5f-4097-879f-b13779fbdc68', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Shapeways: ADD material "Titanium" (FALLBACK generic) to cover orphaned techs: Binder Jetting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('103247e7-ac5f-4097-879f-b13779fbdc68', '016504b7-b2f7-42be-8558-68c01b1749ab')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Shapeways: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('103247e7-ac5f-4097-879f-b13779fbdc68', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- SINTX: ADD material "PLA" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: FDM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('65ef6cd6-fc8e-4de0-a387-9c84c60beebc', 'ee64ec57-3edb-4ec5-8999-849b8aa91953')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- SOLIZE PARTNERS: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: MJF (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('af31de7a-055a-4ede-9ee1-6e88566d3d5b', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- SOLIZE PARTNERS: ADD material "Titanium" (FALLBACK generic) to cover orphaned techs: SLM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('af31de7a-055a-4ede-9ee1-6e88566d3d5b', '016504b7-b2f7-42be-8558-68c01b1749ab')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- THINK3D: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: Material Jetting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('177b476c-03f8-4341-bd22-afdbac981bd6', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- toolcraft AG: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: Injection Molding (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('c1c3e80a-f2ea-4524-a029-f422aac384c4', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Treddy: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('7d3ebc7f-2804-4bd3-bc63-eb2bb135b7be', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- TriMech Advanced Manufacturing Services: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: MJF (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('e3ecfc87-e34a-427f-ab8c-b53e1e54e9fa', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- TriMech Advanced Manufacturing Services: ADD material "PA11 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SAF (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('e3ecfc87-e34a-427f-ab8c-b53e1e54e9fa', '8ffd5af5-d35b-49fc-921f-809b0f893345')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- TriMech Advanced Manufacturing Services: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan); Material Jetting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('e3ecfc87-e34a-427f-ab8c-b53e1e54e9fa', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- TriMech Advanced Manufacturing Services: ADD material "Titanium" (FALLBACK generic) to cover orphaned techs: SLM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('e3ecfc87-e34a-427f-ab8c-b53e1e54e9fa', '016504b7-b2f7-42be-8558-68c01b1749ab')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Vision Miner: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('33ae42d2-24c3-473b-beed-52098aa5f47c', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- WayKen: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('30464f60-1b17-4e8c-8a59-bdb637539357', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- WayKen: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLS (tech-orphan); MJF (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('30464f60-1b17-4e8c-8a59-bdb637539357', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- WayKen: ADD material "Titanium" (FALLBACK generic) to cover orphaned techs: Sheet Metal (tech-orphan); SLM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('30464f60-1b17-4e8c-8a59-bdb637539357', '016504b7-b2f7-42be-8558-68c01b1749ab')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Wenext Technology Co., Ltd: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('d85992a8-c5c0-4a86-a4bb-de474579d21b', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Xometry: ADD material "Aluminum AlSi10Mg" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: Die Casting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('2dcd031d-4f68-4e14-8c54-eea2bf134409', '9b4d1155-a23b-4a88-9ad8-3e38bc83b940')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Xometry: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: Material Jetting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('2dcd031d-4f68-4e14-8c54-eea2bf134409', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- Zeal 3D: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan); DLP (tech-orphan); Material Jetting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('b09a2c00-1ccb-4515-9fdc-4e7ca1f61902', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- zone3Dplus: ADD material "PA12 Nylon" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLS (tech-orphan); MJF (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('cc000001-0004-4000-8000-000000000004', 'bb76b130-2e81-4cd2-bf1b-221132dff805')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- zone3Dplus: ADD material "Standard Resin" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: SLA (tech-orphan); Material Jetting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('cc000001-0004-4000-8000-000000000004', '2f300219-bf55-46f6-bed9-5f9157c8bdee')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- zone3Dplus: ADD material "PLA" (REPRESENTATIVE-FALLBACK: supplier claims tech but no specific material in data) to cover orphaned techs: FDM (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('cc000001-0004-4000-8000-000000000004', 'ee64ec57-3edb-4ec5-8999-849b8aa91953')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- zone3Dplus: ADD material "Titanium" (FALLBACK generic) to cover orphaned techs: Binder Jetting (tech-orphan)
INSERT INTO supplier_materials (supplier_id, material_id)
VALUES ('cc000001-0004-4000-8000-000000000004', '016504b7-b2f7-42be-8558-68c01b1749ab')
ON CONFLICT (supplier_id, material_id) DO NOTHING;

-- ==========================================================
-- REMOVE-MATERIAL: 1 (supplier, material) pairs to delete
--   Material has no compatible AM tech in canonical matrix AND supplier has
--   no molding/casting/cnc evidence. Treated as scraper noise.
-- ==========================================================

-- FORMES ET VOLUMES: REMOVE material "Polyurethane" — Polyurethane has no compatible AM tech in canonical matrix AND supplier metadata/description shows no molding/casting/cnc evidence
DELETE FROM supplier_materials
WHERE supplier_id = '4cfe6688-a4df-4228-9eb0-5d25747b0a22' AND material_id = '5761e97a-75a5-4148-b750-58dad122e758';

COMMIT;
